### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by Jakesta13** [Jakub-Wilk/MulticraftAPI.py#1]
Hello,
When I installed v1.3.2 via pip I got a syntax error.. I found this strange so I tried to use the `example.py` script you have in the gitrepo and it throws the same error.
I'm not python-savvy so I'm not sure how to correct the problem... I had a look at the quotations and they open and close correctly.

`Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from multicraftapi import MulticraftAPI
  File "/usr/local/lib/python2.7/dist-packages/multicraftapi/__init__.py", line 3, in <module>
    from .api import MulticraftAPI
  File "/usr/local/lib/python2.7/dist-packages/multicraftapi/api.py", line 130
    return {'success': False, 'errors': [f'Unknown API method "{function}()"'], 'data': []}
                                                                            ^
SyntaxError: invalid syntax
`

https://github.com/Jakub-Wilk/multicraft-api/blob/293282070c6b83dc415fb7f6fe2643f97ce6c697/multicraftapi/api.py#L130

**Comment by Jakub-Wilk** [comment]
This module is not compatible with python 2. Sorry that I didn't make it clear, I'll add that to the readme.
