### ISSUE TITLE
Getting an error on response

### ISSUE THREAD

**Issue by Moon-developer** [Jakub-Wilk/MulticraftAPI.py#2]
Trying to get this to work on my side. I have api.php enabled in my control panel and generated the API key and giving the correct endpoint but I keep getting `{'success': False, 'errors': ['Invalid API request'], 'data': []}`.

Any ideas why?

**Comment by Jakub-Wilk** [comment]
What request are you sending to the API?

**Comment by Moon-developer** [comment]
Just a simple listUsers. I scouted github for another library and found one by Willsr71. That one works but I can't see why this one doesn't since both are doing the same thing 🤔
