### ISSUE TITLE
Getting Invalid Api Request with any function

### ISSUE THREAD

**Issue by rivermigue** [Jakub-Wilk/MulticraftAPI.py#3]
Hello,

I have tried running some api requests, however I'm receiving a Invalid Api request message:

```
from multicraftapi import MulticraftAPI

# Multicraft setup
MulticraftCon = MulticraftAPI("https://multicraftapp.com/api.php", "user", "1234")

response = MulticraftCon("getServerStatus", "8057")
print(response)
```

{'success': False, 'errors': ['Invalid API request'], 'data': []}

I have also tried the function listUsers which doesnt take any arguments, still same response.

**Comment by Jakub-Wilk** [comment]
Hello, sorry, this is an old project. Perhaps the API works differently now. You'll have to find a different module. I'll archive the repo.
